version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    target-branch: development
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 5
    cooldown:
      semver-patch-days: 3
      semver-minor-days: 7
      semver-major-days: 14

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: development
    cooldown:
      semver-patch-days: 3
      semver-minor-days: 7
      semver-major-days: 14
