services:
  hydra-key-gen:
    container_name: generate-${NETWORK}-hydra-keys
    image: ghcr.io/cardano-scaling/hydra-node:0.22.2
    restart: no
    command:
      [
        "gen-hydra-key",
        "--output-file",
        "/${NETWORK}/keys/${NODE_ID}.hydra"
      ]
    volumes:
      - "../scripts/${NETWORK}:/${NETWORK}"
    networks:
      vending-machine:
  cardano-key-gen:
    container_name: generate-${NETWORK}-cardano-keys
    image: ghcr.io/blinklabs-io/cardano-node
    restart: no
    command:
      [
        "cli",
        "address",
        "key-gen",
        "--verification-key-file",
        "/${NETWORK}/keys/${NODE_ID}.cardano.vk",
        "--signing-key-file",
        "/${NETWORK}/keys/${NODE_ID}.cardano.sk",
      ]
    volumes:
      - "../scripts/${NETWORK}:/${NETWORK}"
    networks:
      vending-machine:
networks:
  vending-machine:
    driver: bridge