services:
  hydra-node:
    container_name: hydra-node-${NETWORK}-${INSTANCE}
    image: ${HYDRA_IMAGE}
    restart: unless-stopped
    command:
      [
        "--node-id", "${NODE_ID}",
        "--listen", "${LISTEN_HOST}:${LISTEN_PORT}",
        "--api-host", "${API_HOST}",
        "--api-port", "${API_PORT}",
        "--hydra-signing-key", "/preprod/keys/${INSTANCE}.hydra.sk",
        "--persistence-dir", "/preprod/hydra/${INSTANCE}",
        "--ledger-protocol-parameters", "/preprod/config/protocol-parameters.json",
        "--cardano-signing-key", "/preprod/keys/${INSTANCE}.cardano.sk",
        "--node-socket","/preprod/config/node.socket",
        "--testnet-magic","${HYDRA_NETWORK_ID}",
        "--hydra-scripts-tx-id","${HYDRA_TX_ID}",
        "--persistence-rotate-after","2250"
      ]
    ports:
      - "${LISTEN_PORT}:${LISTEN_PORT}"
      - "${API_PORT}:${API_PORT}"
    volumes:
      - "${SCRIPTS_DIR}:/preprod"
      - /etc/ssl/certs:/etc/ssl/certs:ro
    networks:
      hydra-network:
  hydra-trp:
    container_name: hydra-trp-${NETWORK}-${INSTANCE}
    image: ${HYDRA_TRP_IMAGE}
    restart: always
    depends_on:
      - hydra-node
    ports:
      - "${TRP_PORT}:${TRP_PORT}"
    environment:
      - RUST_LOG=debug
    volumes:
      - "${SCRIPTS_DIR}/config/${INSTANCE}.toml:/etc/tx3hydra/config.toml"
    networks:
      hydra-network:
  express-api:
    container_name: hydra-express-api-${NETWORK}-${INSTANCE}
    depends_on:
      - hydra-trp
    image: ${EXPRESS_IMAGE}
    restart: unless-stopped
    env_file:
      - ../.env
      - ../.${NETWORK}.env
      - ../.${NETWORK}.${INSTANCE}.env
    environment:
      - NETWORK=${NETWORK}
      - NODE_ENV=development
    ports:
      - "${EXPRESS_PORT}:3000"
    networks:
      hydra-network:
networks:
  hydra-network:
    name: hydra-network-${NETWORK}
    driver: bridge
