services:
  cardano-node:
    container_name: cardano-node-${NETWORK}
    image: ${CARDANO_IMAGE}
    restart: unless-stopped
    environment:
      - NETWORK=${NETWORK}
      - RESTORE_SNAPSHOT=true
    volumes:
      - "${DATA_DIR}/node:/data/db"
      - "${DATA_DIR}/config:/ipc"
      - "${DATA_DIR}/config/cardano-node.json:/opt/cardano/config/${NETWORK}/config.json:ro"
    ports:
      - "${CARDANO_PORT}:3001"
    networks:
      hydra-network:

  cardano-dolos:
    container_name: cardano-dolos-${NETWORK}
    image: ${DOLOS_IMAGE}
    restart: unless-stopped
    depends_on:
      - cardano-node
    command: ["daemon"]
    ports:
      - "${DOLOS_TRP_PORT}:${DOLOS_TRP_PORT}"
      - "${DOLOS_GRPC_PORT}:${DOLOS_GRPC_PORT}"
    volumes:
      - "${DATA_DIR}/dolos:/data"
      - "${DATA_DIR}/config/dolos.toml:/etc/dolos/dolos.toml:ro"
    networks:
      hydra-network:

networks:
  hydra-network:
    name: hydra-network-${NETWORK}
    driver: bridge
