FROM node:22-alpine

RUN apk add --no-cache bash

WORKDIR /usr/src/app

# Copy package metadata first to leverage layer caching
COPY ../package*.json ./

# Run npm install
RUN npm install

# Copy tsconfig if used
COPY ../tsconfig.json ./

# Copy source
COPY ../packages/middleware/src ./src

EXPOSE 3000

ENV NODE_ENV=development

CMD ["npx", "tsx", "watch", "src/index.ts"]