services:
  hydra-node:
    container_name: hydra-node-${NETWORK}
    image: ${HYDRA_IMAGE}
    restart: unless-stopped
    command:
      [
        "--node-id",
        "${NODE_ID}",
        "--listen",
        "${LISTEN_HOST}:${LISTEN_PORT}",
        "--api-host",
        "${API_HOST}",
        "--api-port",
        "${API_PORT}",
        "--hydra-signing-key",
        "/offline/keys/${NODE_ID}.hydra.sk",
        "--persistence-dir",
        "/offline/hydra",
        "--ledger-protocol-parameters",
        "/offline/config/protocol-parameters.json",
        "--offline-head-seed",
        "0001",
        "--initial-utxo",
        "/offline/config/utxo.json",
      ]
    ports:
      - "${LISTEN_PORT}:${LISTEN_PORT}"
      - "${API_PORT}:${API_PORT}"
    volumes:
      - "${SCRIPTS_DIR}:/offline"
    networks:
      hydra-network:

  hydra-trp:
    container_name: hydra-trp-${NETWORK}
    image: ${HYDRA_TRP_IMAGE}
    restart: always
    depends_on:
      - hydra-node
    ports:
      - "${TRP_PORT}:${TRP_PORT}"
    environment:
      - RUST_LOG=debug
    volumes:
      - "${SCRIPTS_DIR}/config:/etc/tx3hydra"
    networks:
      hydra-network:

networks:
  hydra-network:
    name: hydra-network-${NETWORK}
    driver: bridge
