services:
  hydra-node:
    container_name: hydra-node-${NETWORK}
    image: ${HYDRA_IMAGE}
    restart: unless-stopped
    command:
      [
        "--node-id",
        "${NODE_ID}",
        "--listen",
        "${LISTEN_HOST}:${LISTEN_PORT}",
        "--api-host",
        "${API_HOST}",
        "--api-port",
        "${API_PORT}",
        "--hydra-signing-key",
        "/${NETWORK}/keys/${NODE_ID}.hydra.sk",
        "--persistence-dir",
        "/${NETWORK}/hydra",
        "--ledger-protocol-parameters",
        "/${NETWORK}/config/protocol-parameters.json",
        "--offline-head-seed",
        "0001",
        "--initial-utxo",
        "/${NETWORK}/config/utxo.json",
        "--persistence-rotate-after",
        "1000"
      ]
    ports:
      - "${LISTEN_PORT}:${LISTEN_PORT}"
      - "${API_PORT}:${API_PORT}"
    volumes:
      - "${DATA_DIR}/config:/${NETWORK}/config:ro"
      - "${DATA_DIR}/instances/${INSTANCE}/keys:/${NETWORK}/keys:ro"
      - "${DATA_DIR}/instances/${INSTANCE}/hydra:/${NETWORK}/hydra"
    networks:
      hydra-network:

  hydra-trp:
    container_name: hydra-trp-${NETWORK}
    image: ${HYDRA_TRP_IMAGE}
    restart: always
    depends_on:
      - hydra-node
    ports:
      - "${TRP_PORT}:${TRP_PORT}"
    environment:
      - RUST_LOG=debug
    volumes:
      - "${DATA_DIR}/instances/${INSTANCE}/config:/etc/tx3hydra:ro"
    networks:
      hydra-network:

  express-api:
    container_name: hydra-express-api-${NETWORK}
    depends_on:
      - hydra-trp
    image: ${EXPRESS_IMAGE:-hydra-express-local}
    build:
      context: ..
      dockerfile: docker/Dockerfile.express
    working_dir: /usr/src/app
    ports:
      - "${EXPRESS_PORT}:${EXPRESS_PORT}"
    env_file:
      - ../.env
      - ../.${NETWORK}.env
    environment:
      - NETWORK=${NETWORK}
      - NODE_ENV=development
      - HYDRA_ADMIN_KEY_FILE=/${NETWORK}/keys/${NODE_ID}.cardano.sk
      - IPFS_STAGING_DIR=/ipfs-staging
    volumes:
      - ..:/usr/src/app:delegated
      - /usr/src/app/node_modules
      - "${DATA_DIR}/instances/${INSTANCE}/keys:/${NETWORK}/keys:ro"
      - "${DATA_DIR}/instances/${INSTANCE}/ipfs-staging:/ipfs-staging"
    command: [ "npx", "tsx", "watch", "examples/local-currency/index.ts" ]
    networks:
      hydra-network:
      ipfs-network:
    restart: unless-stopped

networks:
  hydra-network:
    name: hydra-network-${NETWORK}
    driver: bridge
  ipfs-network:
    external: true
