x-keys: &keys
  volumes:
    - "../scripts/${NETWORK}/keys:/keys"
  working_dir: /keys

services:
  hydra-key-gen:
    <<: *keys
    image: ${HYDRA_IMAGE}
    restart: "no"
    command:
      [
        "gen-hydra-key",
        "--output-file",
        "./${NODE_ID}.hydra"
      ]
  cardano-key-gen:
    <<: *keys
    image: ${CARDANO_IMAGE}
    restart: "no"
    command:
      [
        "cli",
        "address",
        "key-gen",
        "--verification-key-file",
        "./${NODE_ID}.cardano.vk",
        "--signing-key-file",
        "./${NODE_ID}.cardano.sk"
      ]
  cardano-addr-gen-mainnet:
    <<: *keys
    image: ${CARDANO_IMAGE}
    restart: "no"
    command:
      [
        "cli",
        "address",
        "build",
        "--payment-verification-key-file",
        "./${NODE_ID}.cardano.vk",
        "--out-file",
        "./${NODE_ID}.cardano.addr",
        "--mainnet"
      ]
  cardano-addr-gen-testnet:
    <<: *keys
    image: ${CARDANO_IMAGE}
    restart: "no"
    command:
      [
        "cli",
        "address",
        "build",
        "--payment-verification-key-file",
        "./${NODE_ID}.cardano.vk",
        "--out-file",
        "./${NODE_ID}.cardano.addr",
        "--testnet-magic",
        "${CARDANO_TESTNET_MAGIC:-1}"
      ]