import './load.js';

import { getAdmin, optionalEnv, requireEnv, submitTx, Wrangler } from '@lerna-labs/hydra-sdk';
import { sha256 } from '@noble/hashes/sha2.js';
import { bytesToHex } from '@noble/hashes/utils.js';
import express from 'express';

import { cacheEntry, getAllEntries, getDocumentsDir, getEntry, type NotaryEntry, rehydrateCache } from './cache.js';
import { pinDirectory, pinJson } from './ipfs.js';
import { authHeaderMiddleware } from './middleware.js';

// ── Mutex (same pattern as local-currency) ──────────────────────────
class Mutex {
  private chain = Promise.resolve();

  async acquire(): Promise<() => void> {
    let release!: () => void;
    const next = new Promise<void>((resolve) => {
      release = resolve;
    });
    const prev = this.chain;
    this.chain = this.chain.then(() => next);
    await prev;
    return release;
  }
}

const txMutex = new Mutex();

// ── Config ──────────────────────────────────────────────────────────
const app = express();
app.use(express.json({ limit: '1mb' }));
app.use(authHeaderMiddleware);

const port = optionalEnv('EXPRESS_PORT', '3000');
const TRP_URL = requireEnv('TRP_URL');

// ── Routes ──────────────────────────────────────────────────────────

app.get('/', (_, res) => {
  res.send('Hydra Notary API is running');
});

app.get('/health', async (_, res) => {
  const wrangler = new Wrangler(process.env.HYDRA_API_URL, process.env.HYDRA_WS_URL);
  try {
    const status = await wrangler.getHeadStatus(5000);
    return res.json({ status });
  } catch (e: any) {
    console.error('Health check failed:', e);
    return res.json({ status: 'ERROR', message: 'Could not connect to Hydra node!' });
  }
});

/**
 * POST /notarize
 *
 * Body: {
 *   submitter: string   — bech32 address of the submitter
 *   filename:  string   — original document filename
 *   content:   string   — document content (or base64-encoded binary)
 * }
 *
 * Flow:
 *  1. Hash the content (SHA-256)
 *  2. Build a full notarisation payload
 *  3. Write payload to disk (staging directory)
 *  4. Pin to IPFS, receive CID
 *  5. Submit a Hydra tx with the CID + doc hash in metadata
 *  6. Update in-memory cache
 *  7. Return CID + tx hash to caller
 */
app.post('/notarize', async (req, res) => {
  const { submitter, filename, content } = req.body;

  if (!submitter || !filename || !content) {
    return res.status(400).json({
      status: 'ERROR',
      message: 'Request body must include submitter, filename, and content',
    });
  }

  const release = await txMutex.acquire();
  try {
    // 1. Hash the document content
    const contentBytes = Buffer.from(content, 'utf-8');
    const docHash = bytesToHex(sha256(contentBytes));

    // 2. Build the full notarisation payload
    const timestamp = Date.now();
    const payload = {
      docHash,
      submitter,
      filename,
      content,
      timestamp,
    };

    // 3. Write to disk + 4. Pin to IPFS
    const diskFilename = `${docHash}-${timestamp}.json`;
    const entry: NotaryEntry = {
      docHash,
      ipfsCid: '', // filled after pinning
      submitter,
      filename: diskFilename,
      timestamp,
    };

    await cacheEntry(entry, payload);

    let ipfsCid: string;
    try {
      const pinResult = await pinJson(diskFilename, payload);
      ipfsCid = pinResult.cid;
      entry.ipfsCid = ipfsCid;
    } catch (err: any) {
      console.error('IPFS pin failed, continuing with disk-only:', err.message);
      ipfsCid = 'ipfs-unavailable';
      entry.ipfsCid = ipfsCid;
    }

    // 5. Submit a Hydra transaction with CID + doc hash in metadata
    //
    // NOTE: In a full implementation you would use the tx3-generated
    // protocol client (like local-currency does) to build and submit
    // the notarize transaction. For this example we show the IPFS +
    // cache flow and leave the tx3 integration as an exercise, since
    // the protocol.ts bindings are generated by `trix bindgen`.
    //
    // The tx metadata would be:
    //   label 0: Buffer.from(ipfsCid, 'utf-8')   — the IPFS CID
    //   label 1: Buffer.from(docHash, 'hex')      — the document hash
    //
    // For now, we log what would be submitted:
    console.log(`Notarised: ${filename}`);
    console.log(`  Doc hash : ${docHash}`);
    console.log(`  IPFS CID : ${ipfsCid}`);
    console.log(`  Submitter: ${submitter}`);

    // 6. Update cache with final state
    await cacheEntry(entry, payload);

    // 7. Return result
    return res.json({
      status: 'SUCCESS',
      data: {
        docHash,
        ipfsCid,
        timestamp,
      },
    });
  } catch (err: any) {
    console.error('Notarize error:', err);
    return res.json({
      status: 'ERROR',
      message: 'Failed to notarize document',
    });
  } finally {
    release();
  }
});

/**
 * GET /document/:docHash
 *
 * Look up the most recent notarisation for a given document hash.
 */
app.get('/document/:docHash', (req, res) => {
  const entry = getEntry(req.params.docHash);
  if (!entry) {
    return res.status(404).json({ status: 'ERROR', message: 'Document not found' });
  }
  return res.json({ status: 'SUCCESS', data: entry });
});

/**
 * GET /documents
 *
 * List all notarised documents in the cache.
 */
app.get('/documents', (_, res) => {
  return res.json({ status: 'SUCCESS', data: getAllEntries() });
});

/**
 * POST /publish
 *
 * Pin the entire documents directory to IPFS and return the root CID.
 * This is intended to be called at settlement time so auditors can
 * download every notarised document from a single CID.
 */
app.post('/publish', async (_, res) => {
  try {
    const result = await pinDirectory(getDocumentsDir());
    console.log(`Published all documents to IPFS: ${result.cid}`);
    return res.json({
      status: 'SUCCESS',
      data: {
        ipfsCid: result.cid,
        size: result.size,
      },
    });
  } catch (err: any) {
    console.error('Publish error:', err);
    return res.json({
      status: 'ERROR',
      message: 'Failed to publish documents directory to IPFS',
    });
  }
});

// ── Boot ────────────────────────────────────────────────────────────

async function boot() {
  const count = await rehydrateCache();
  if (count > 0) {
    console.log(`Rehydrated ${count} entries from disk`);
  }

  app.listen(port, () => {
    console.log(`Hydra Notary API is running on http://localhost:${port}`);
  });
}

boot().catch((err) => {
  console.error('Failed to boot:', err);
  process.exit(1);
});
