#!/usr/bin/env bash
set -euo pipefail

# ────────────────────────────────────────────────
# Generate Prometheus scrape config from active instance .env files.
#
# Scans for .{network}.{instance}.env files, extracts MONITORING_PORT,
# and writes docker/monitoring/prometheus.yml with the correct targets.
#
# Usage:
#   ./scripts/generate-prometheus-config.sh
# ────────────────────────────────────────────────

OUTPUT="docker/monitoring/prometheus.yml"

# Prometheus runs with network_mode: host, so it can reach host ports via localhost.
DOCKER_HOST_IP="localhost"

cat > "${OUTPUT}" <<'HEADER'
# Auto-generated by scripts/generate-prometheus-config.sh
# Re-run after adding/removing instances.

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'hydra-nodes'
    metrics_path: /metrics
    static_configs:
HEADER

FOUND=0

for envfile in .*.*.env; do
  # Skip example files
  [[ "${envfile}" == .example.* ]] && continue

  # Extract network and instance from filename: .{network}.{instance}.env
  basename="${envfile#.}"        # remove leading dot
  basename="${basename%.env}"    # remove trailing .env

  # Must have exactly one dot remaining (network.instance)
  if [[ "${basename}" != *.* ]]; then
    continue
  fi

  NETWORK="${basename%%.*}"
  INSTANCE="${basename#*.}"

  # Skip if no MONITORING_PORT defined
  PORT=$(grep -E "^MONITORING_PORT=" "${envfile}" 2>/dev/null | head -n1 | cut -d= -f2- || true)
  if [[ -z "${PORT}" ]]; then
    continue
  fi

  cat >> "${OUTPUT}" <<EOF
      - targets: ['${DOCKER_HOST_IP}:${PORT}']
        labels:
          network: '${NETWORK}'
          instance: '${INSTANCE}'
EOF

  FOUND=$((FOUND + 1))
  echo "  ✅ ${NETWORK}/${INSTANCE} → ${DOCKER_HOST_IP}:${PORT}"
done

if [[ ${FOUND} -eq 0 ]]; then
  echo "⚠️  No instance .env files with MONITORING_PORT found."
  echo "   Create instances first: make NETWORK=<network> INSTANCE=<id> create-instance"
else
  echo ""
  echo "📊 Wrote ${OUTPUT} with ${FOUND} target(s)"
  echo "   Restart monitoring to pick up changes: make monitoring-restart"
fi
